[tool.poetry]
name = "mnist-mlops"
version = "0.1.0"
description = ""
authors = ["Shady-Abdelaziz <Shady75738@yahoo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scikit-learn = "^1.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
